name: Base CI

env:
  GO_VERSION: 1.21
  BIN_NAME: you_app # TODO: set you app executable name

on:
  push:
    branches:
      - main
      - dev/*/main
      - *   # TODO: you can set any required branch to run test an lints
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Verify dependencies
        run: go mod verify
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: staticcheck ./...
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Run golint
        run: golint ./...
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
  vet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Verify dependencies
        run: go mod verify
      - name: Run go vet
        run: go vet ./...
  test:
    needs: [vet, lint, golangci-lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Verify dependencies
        run: go mod verify
      - name: Run tests
        run: go test -race -vet=off ./...
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Verify dependencies
        run: go mod verify
      - name: Run build
        run: make build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./bin/BIN_NAME